# name: My First Workflow 

# on: 
#   push:
#   pull_request:

# jobs: 
#   say-hello:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Print message
#         run: echo "Hello, GitHub Actions!"

#       - name: Print second message
#         run: echo "Hello there!"

#   say-bye:
#     runs-on: ubuntu-latest
#     needs: say-hello

#     steps:
#       - name: Print bye message
#         run: echo "Say bye"


# name: My First Workflow 

# on: pull_request

# jobs: 
#   say-hello:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Print message
#         run: echo "Hello, GitHub Actions!"

#       - name: Print second message
#         run: echo "Hello there!"

#   say-bye:
#     runs-on: ubuntu-latest
#     needs: say-hello

#     steps:
#       - name: Print bye message
#         run: echo "Say bye"



# name: My First Workflow

# on: pull_request

# jobs: 
#   test:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: List file
#         run: ls

#       - name: Setup node
#         uses: actions/setup-node@v4
#         with: 
#           node-version: 24
#           cache: "npm"

#       - name: Check node version
#         run: node -v

#       - name: Download dependencies
#         run: npm i

#       - name: Run test
#         run: npm run test

#   deploy-app:
#     runs-on: ubuntu-latest
#     needs: test
    
#     steps:
#       - name: deploy
#         run: echo "deploying"


# name: My First Workflow

# on: push

# jobs: 
#   test:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Setup node
#         uses: actions/setup-node@v4
#         with: 
#           node-version: 24
#           cache: "npm"

#       - name: Install dependencies
#         run: npm install

#       - name: Run ESLint
#         run: npm run lint

#       - name: Run tests
#         run: npm run test

#       - name: Build project
#         run: npm run build

#   deploy-app:
#     runs-on: ubuntu-latest
#     needs: test
    
#     steps:
#       - name: deploy
#         run: echo "deploying"

name: My First Workflow

on: push

jobs: 
  upload-file:
    runs-on: ubuntu-latest

    steps:
      - name: Create file
        run: touch file1.txt

      - name: Upload file
        uses: actions/upload-artifact@v4
        with: 
          name: my-file

  download-file:
    runs-on: ubuntu-latest
    needs: upload-file
    
    steps:
      - name: Download file
        uses: actions/download-artifact@v4
        with: 
          name: my-file
          path: file1.txt

      - name: Read file
        run: cat file1.txt